Repository newrelic/newrelic-telemetry-sdk-node, pull requests merged in 2021-04, with the labels that each got.

#48 feat: Add Support for Event API
  src/telemetry/events/batch.ts
  src/telemetry/events/client.ts
  src/telemetry/events/event.ts
  src/telemetry/events/index.ts
  src/telemetry/index.ts
  tests/server-integration/event-client.tap.ts
  tests/server-integration/insights-results.ts
  tests/unit/events/batch.tap.ts
  tests/unit/events/client.tap.ts
  tests/unit/events/event.tap.ts
Labels: risk: low, semver: minor

#51 Fix nr error checking
  tests/server-integration/insights-results.ts
Labels: risk: low

#54 Release/v0.4.0
  CHANGELOG.md
Labels: risk: low, semver: minor

#56 Increase log-client integration test verification wait time to 3 seconds.
  tests/server-integration/log-client.tap.ts
Labels: risk: none, semver: patch
